services:
  - type: web
    name: springboot-llb-webapp
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d267o42li9vc73cuv27g-a.oregon-postgres.render.com/llb_db
      - key: SPRING_DATASOURCE_USERNAME
        value: llb_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 1fVoyD3yVhYpZYgzjOT2AwiVCD19kpsA
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
